# Generated by Django 4.0.4 on 2022-05-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_location_date_created_location_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='title',
        ),
    ]
