# Generated by Django 4.0.4 on 2022-05-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_name_location_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='uniqueId',
        ),
    ]
