# Generated by Django 4.0.4 on 2022-05-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_location_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='name',
        ),
    ]
